import os
import logging
import uuid
import certifi
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient

logger = logging.getLogger(__name__)
MONGO_URL = os.environ.get(
    "MONGO_URL",
    "mongodb+srv://vicezealor_db_user:bQHNL5fFkLKSgAxO@cluster0.ucm88sl.mongodb.net/?appName=Cluster0",
)
DB_NAME = os.environ.get("DB_NAME", "qmeal_db")
client = AsyncIOMotorClient(
    MONGO_URL,
    tls=True,
    tlsAllowInvalidCertificates=True,
    tlsCAFile=certifi.where(),
    serverSelectionTimeoutMS=5000,
)
db = client[DB_NAME]


async def get_db():
    return db


async def seed_data():
    try:
        existing = await db.restaurants.count_documents({})
        if existing > 0:
            return
        restaurants = [
            {
                "restaurant_id": "rest_001",
                "name": "Bella Italia",
                "description": "Authentic Italian cuisine with handmade pasta and wood-fired pizzas",
                "cuisine_type": "Italian",
                "rating": 4.7,
                "review_count": 234,
                "price_level": 2,
                "image_url": "https://images.unsplash.com/photo-1615719413546-198b25453f85",
                "address": "123 Main Street, Downtown",
                "latitude": 40.7128,
                "longitude": -74.006,
                "delivery_time_min": 25,
                "delivery_time_max": 40,
                "delivery_fee": 2.99,
                "is_open": True,
                "created_at": datetime.now(timezone.utc),
            },
            {
                "restaurant_id": "rest_002",
                "name": "Tokyo Ramen House",
                "description": "Traditional Japanese ramen and authentic Asian dishes",
                "cuisine_type": "Japanese",
                "rating": 4.8,
                "review_count": 189,
                "price_level": 2,
                "image_url": "https://images.unsplash.com/photo-1676300185004-c31cf62d3bc8",
                "address": "456 Oak Avenue, Midtown",
                "latitude": 40.758,
                "longitude": -73.9855,
                "delivery_time_min": 20,
                "delivery_time_max": 35,
                "delivery_fee": 1.99,
                "is_open": True,
                "created_at": datetime.now(timezone.utc),
            },
            {
                "restaurant_id": "rest_003",
                "name": "Burger Republic",
                "description": "Gourmet burgers made with premium Angus beef and fresh ingredients",
                "cuisine_type": "American",
                "rating": 4.5,
                "review_count": 456,
                "price_level": 1,
                "image_url": "https://images.unsplash.com/photo-1651440204227-a9a5b9d19712",
                "address": "789 Elm Street, Uptown",
                "latitude": 40.7829,
                "longitude": -73.9654,
                "delivery_time_min": 15,
                "delivery_time_max": 30,
                "delivery_fee": 0.99,
                "is_open": True,
                "created_at": datetime.now(timezone.utc),
            },
            {
                "restaurant_id": "rest_004",
                "name": "Spice Garden",
                "description": "Aromatic Indian curries and tandoori specialties",
                "cuisine_type": "Indian",
                "rating": 4.6,
                "review_count": 178,
                "price_level": 2,
                "image_url": "https://images.unsplash.com/photo-1694184191737-778bc1b5c4e8",
                "address": "321 Spice Lane, East Side",
                "latitude": 40.7489,
                "longitude": -73.968,
                "delivery_time_min": 30,
                "delivery_time_max": 45,
                "delivery_fee": 2.49,
                "is_open": True,
                "created_at": datetime.now(timezone.utc),
            },
            {
                "restaurant_id": "rest_005",
                "name": "Le Petit Bistro",
                "description": "French cuisine with a modern twist in an elegant setting",
                "cuisine_type": "French",
                "rating": 4.9,
                "review_count": 98,
                "price_level": 4,
                "image_url": "https://images.unsplash.com/photo-1683538503204-fec7fc504067",
                "address": "555 Boulevard Ave, West End",
                "latitude": 40.7614,
                "longitude": -73.9776,
                "delivery_time_min": 35,
                "delivery_time_max": 50,
                "delivery_fee": 4.99,
                "is_open": True,
                "created_at": datetime.now(timezone.utc),
            },
            {
                "restaurant_id": "rest_006",
                "name": "Taco Fiesta",
                "description": "Authentic Mexican street food and margaritas",
                "cuisine_type": "Mexican",
                "rating": 4.4,
                "review_count": 312,
                "price_level": 1,
                "image_url": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47",
                "address": "777 Fiesta Way, South Side",
                "latitude": 40.7282,
                "longitude": -73.7949,
                "delivery_time_min": 20,
                "delivery_time_max": 35,
                "delivery_fee": 1.49,
                "is_open": True,
                "created_at": datetime.now(timezone.utc),
            },
            {
                "restaurant_id": "rest_007",
                "name": "Dragon Palace",
                "description": "Traditional Chinese cuisine with dim sum and Cantonese favorites",
                "cuisine_type": "Chinese",
                "rating": 4.3,
                "review_count": 267,
                "price_level": 2,
                "image_url": "https://images.unsplash.com/photo-1563245372-f21724e3856d",
                "address": "888 Dragon Street, Chinatown",
                "latitude": 40.7157,
                "longitude": -73.997,
                "delivery_time_min": 25,
                "delivery_time_max": 40,
                "delivery_fee": 2.29,
                "is_open": True,
                "created_at": datetime.now(timezone.utc),
            },
            {
                "restaurant_id": "rest_008",
                "name": "Mediterranean Grill",
                "description": "Fresh Mediterranean flavors with grilled meats and seafood",
                "cuisine_type": "Mediterranean",
                "rating": 4.6,
                "review_count": 145,
                "price_level": 3,
                "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947",
                "address": "999 Olive Road, Harbor District",
                "latitude": 40.7023,
                "longitude": -74.0156,
                "delivery_time_min": 30,
                "delivery_time_max": 45,
                "delivery_fee": 3.49,
                "is_open": True,
                "created_at": datetime.now(timezone.utc),
            },
        ]
        await db.restaurants.insert_many(restaurants)
        menu_items = [
            {
                "item_id": "item_001",
                "restaurant_id": "rest_001",
                "name": "Margherita Pizza",
                "description": "Fresh mozzarella, tomato sauce, and basil",
                "price": 14.99,
                "category": "Pizza",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_002",
                "restaurant_id": "rest_001",
                "name": "Spaghetti Carbonara",
                "description": "Creamy pasta with bacon and parmesan",
                "price": 16.99,
                "category": "Pasta",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_003",
                "restaurant_id": "rest_001",
                "name": "Tiramisu",
                "description": "Classic Italian dessert with coffee and mascarpone",
                "price": 8.99,
                "category": "Desserts",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_004",
                "restaurant_id": "rest_001",
                "name": "Bruschetta",
                "description": "Toasted bread with tomatoes, garlic, and olive oil",
                "price": 9.99,
                "category": "Appetizers",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_005",
                "restaurant_id": "rest_001",
                "name": "Lasagna",
                "description": "Layers of pasta, meat sauce, and cheese",
                "price": 18.99,
                "category": "Pasta",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_006",
                "restaurant_id": "rest_002",
                "name": "Tonkotsu Ramen",
                "description": "Rich pork bone broth with chashu and soft egg",
                "price": 15.99,
                "category": "Ramen",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_007",
                "restaurant_id": "rest_002",
                "name": "Gyoza (6 pcs)",
                "description": "Pan-fried pork dumplings",
                "price": 8.99,
                "category": "Appetizers",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_008",
                "restaurant_id": "rest_002",
                "name": "Chicken Katsu Curry",
                "description": "Crispy chicken cutlet with Japanese curry",
                "price": 16.99,
                "category": "Main Dishes",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_009",
                "restaurant_id": "rest_002",
                "name": "Miso Soup",
                "description": "Traditional Japanese soup with tofu and seaweed",
                "price": 4.99,
                "category": "Soups",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_010",
                "restaurant_id": "rest_002",
                "name": "Spicy Miso Ramen",
                "description": "Spicy miso broth with ground pork and corn",
                "price": 16.99,
                "category": "Ramen",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_011",
                "restaurant_id": "rest_003",
                "name": "Classic Smash Burger",
                "description": "Double patty with cheese, lettuce, tomato",
                "price": 12.99,
                "category": "Burgers",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_012",
                "restaurant_id": "rest_003",
                "name": "Bacon BBQ Burger",
                "description": "Angus beef with bacon, cheddar, and BBQ sauce",
                "price": 14.99,
                "category": "Burgers",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_013",
                "restaurant_id": "rest_003",
                "name": "Loaded Fries",
                "description": "Crispy fries with cheese, bacon, and sour cream",
                "price": 8.99,
                "category": "Sides",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_014",
                "restaurant_id": "rest_003",
                "name": "Onion Rings",
                "description": "Beer-battered onion rings",
                "price": 6.99,
                "category": "Sides",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_015",
                "restaurant_id": "rest_003",
                "name": "Milkshake",
                "description": "Choose vanilla, chocolate, or strawberry",
                "price": 5.99,
                "category": "Drinks",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_016",
                "restaurant_id": "rest_004",
                "name": "Butter Chicken",
                "description": "Tender chicken in creamy tomato sauce",
                "price": 16.99,
                "category": "Main Dishes",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_017",
                "restaurant_id": "rest_004",
                "name": "Lamb Biryani",
                "description": "Fragrant basmati rice with spiced lamb",
                "price": 18.99,
                "category": "Rice Dishes",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_018",
                "restaurant_id": "rest_004",
                "name": "Garlic Naan",
                "description": "Fresh baked bread with garlic butter",
                "price": 3.99,
                "category": "Bread",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_019",
                "restaurant_id": "rest_004",
                "name": "Samosa (2 pcs)",
                "description": "Crispy pastry filled with spiced potatoes",
                "price": 5.99,
                "category": "Appetizers",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_020",
                "restaurant_id": "rest_004",
                "name": "Palak Paneer",
                "description": "Cottage cheese in spinach gravy",
                "price": 14.99,
                "category": "Main Dishes",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_021",
                "restaurant_id": "rest_005",
                "name": "Duck Confit",
                "description": "Slow-cooked duck leg with roasted potatoes",
                "price": 32.99,
                "category": "Main Dishes",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_022",
                "restaurant_id": "rest_005",
                "name": "French Onion Soup",
                "description": "Classic soup with melted gruyere cheese",
                "price": 12.99,
                "category": "Soups",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_023",
                "restaurant_id": "rest_005",
                "name": "Steak Frites",
                "description": "Grilled ribeye with herb butter and fries",
                "price": 38.99,
                "category": "Main Dishes",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_024",
                "restaurant_id": "rest_005",
                "name": "Crème Brûlée",
                "description": "Classic vanilla custard with caramelized sugar",
                "price": 10.99,
                "category": "Desserts",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_025",
                "restaurant_id": "rest_005",
                "name": "Escargot",
                "description": "Garlic butter snails in shell",
                "price": 16.99,
                "category": "Appetizers",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_026",
                "restaurant_id": "rest_006",
                "name": "Street Tacos (3)",
                "description": "Choice of carnitas, chicken, or steak",
                "price": 10.99,
                "category": "Tacos",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_027",
                "restaurant_id": "rest_006",
                "name": "Burrito Bowl",
                "description": "Rice, beans, protein, and toppings",
                "price": 12.99,
                "category": "Bowls",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_028",
                "restaurant_id": "rest_006",
                "name": "Guacamole & Chips",
                "description": "Fresh made guacamole with tortilla chips",
                "price": 8.99,
                "category": "Appetizers",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_029",
                "restaurant_id": "rest_006",
                "name": "Quesadilla",
                "description": "Grilled tortilla with cheese and protein",
                "price": 11.99,
                "category": "Main Dishes",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_030",
                "restaurant_id": "rest_006",
                "name": "Churros",
                "description": "Fried dough with cinnamon sugar and chocolate",
                "price": 6.99,
                "category": "Desserts",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_031",
                "restaurant_id": "rest_007",
                "name": "Kung Pao Chicken",
                "description": "Spicy chicken with peanuts and peppers",
                "price": 15.99,
                "category": "Main Dishes",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_032",
                "restaurant_id": "rest_007",
                "name": "Dim Sum Platter",
                "description": "Assorted dumplings and buns",
                "price": 18.99,
                "category": "Dim Sum",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_033",
                "restaurant_id": "rest_007",
                "name": "Peking Duck",
                "description": "Crispy duck with pancakes and hoisin",
                "price": 38.99,
                "category": "Specialties",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_034",
                "restaurant_id": "rest_007",
                "name": "Fried Rice",
                "description": "Wok-fried rice with egg and vegetables",
                "price": 10.99,
                "category": "Rice Dishes",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_035",
                "restaurant_id": "rest_007",
                "name": "Spring Rolls (4)",
                "description": "Crispy vegetable spring rolls",
                "price": 7.99,
                "category": "Appetizers",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_036",
                "restaurant_id": "rest_008",
                "name": "Grilled Lamb Chops",
                "description": "Marinated lamb with Mediterranean herbs",
                "price": 28.99,
                "category": "Main Dishes",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_037",
                "restaurant_id": "rest_008",
                "name": "Mixed Grill Platter",
                "description": "Chicken, lamb, and beef kebabs",
                "price": 24.99,
                "category": "Main Dishes",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_038",
                "restaurant_id": "rest_008",
                "name": "Hummus & Pita",
                "description": "Creamy hummus with warm pita bread",
                "price": 8.99,
                "category": "Appetizers",
                "is_available": True,
                "is_popular": True,
            },
            {
                "item_id": "item_039",
                "restaurant_id": "rest_008",
                "name": "Greek Salad",
                "description": "Fresh vegetables with feta and olives",
                "price": 11.99,
                "category": "Salads",
                "is_available": True,
                "is_popular": False,
            },
            {
                "item_id": "item_040",
                "restaurant_id": "rest_008",
                "name": "Baklava",
                "description": "Honey-soaked phyllo pastry with nuts",
                "price": 7.99,
                "category": "Desserts",
                "is_available": True,
                "is_popular": False,
            },
        ]
        await db.menu_items.insert_many(menu_items)
        await db.users.create_index("email", unique=True, sparse=True)
        await db.users.create_index("phone", unique=True, sparse=True)
        await db.users.create_index("user_id", unique=True)
        await db.restaurants.create_index("restaurant_id", unique=True)
        await db.menu_items.create_index("restaurant_id")
        await db.orders.create_index("user_id")
        await db.favorites.create_index(
            [("user_id", 1), ("restaurant_id", 1)], unique=True
        )
        await db.notifications.create_index("user_id")
        logger.info("Database seeded successfully.")
    except Exception as e:
        logger.exception(f"Seed error: {e}")